# Use the official PostgreSQL image
FROM postgres:latest

# Set environment variables
ENV POSTGRES_USER pong
ENV POSTGRES_PASSWORD ping
ENV POSTGRES_DB pong_database

# Expose the PostgreSQL port
EXPOSE 5432