# Generated by Django 5.0.1 on 2024-01-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('game', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('score', models.BooleanField()),
                ('ranking', models.IntegerField()),
            ],
        ),
    ]
